version: "3"
services:
  geth:
    container_name: geth
    image: ethereum/client-go
    volumes:
      - "/mnt/eth-data/ethereum/execution/geth:/root"
    ports:
      - "8545:8545"
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "8551:8551"
    restart: always
    hostname: geth
    command: --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts * --http --http.api eth,net,engine,admin --authrpc.jwtsecret /root/jwt.hex --syncmode snap

  beacon-chain:
    container_name: beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    restart: always
    hostname: beacon-chain
    depends_on:
      - geth
    command: --accept-terms-of-use --jwt-secret=/root/jwt.hex --checkpoint-sync-url=https://sync.invis.tools --execution-endpoint=http://geth:8551 --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0
    ports:
      - "4000:4000"
      - "13000:13000/tcp"
      - "12000:12000/udp"
    volumes:
      - "/mnt/eth-data/ethereum/consensus/prysm:/root"
